# Site settings
title: Department of Cybernetics and Robotics
description: >-
  Department of Cybernetics and Robotics,
  Wroc≈Çaw University of Science and Technology
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-polyglot

# Polyglot settings
languages: ["pl", "en"]
default_lang: "pl"
exclude_from_localization: ["javascript", "images", "css", "public", "vendor"]
parallel_localization: false

# Collections
collections:
  faculty:
    output: true
    permalink: /faculty/:name/
  research:
    output: true
    permalink: /research/:name/
  laboratories:
    output: true
    permalink: /laboratories/:name/
  seminars:
    output: true
    permalink: /seminars/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "faculty"
    values:
      layout: "faculty"
  - scope:
      path: ""
      type: "research"
    values:
      layout: "research"
  - scope:
      path: ""
      type: "laboratories"
    values:
      layout: "laboratory"
  - scope:
      path: ""
      type: "seminars"
    values:
      layout: "seminar"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
